version: "2"
services:
  backend:
    build: nodemachine
    command: sh -c 'npm install --no-bin-links; npm rebuild; npm start'
    ports:
      - "8080:8080"
    volumes:
      - ../backend:/app

  frontend:
    build: nodemachine
    command: sh -c 'npm install --no-bin-links; npm i -g react-scripts; npm start'
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"